# Generated by Django 5.0.6 on 2024-06-20 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lims_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Book",
            new_name="AddBook",
        ),
    ]
